2022-08-05 09:56:48,942 INFO  [restartedMain] (StartupInfoLogger.java:55)- Starting SwhyPracticeApplication using Java 11.0.14 on SK-20211029DMIT with PID 11948 (F:\swhyPractice\target\classes started by Administrator in F:\swhyPractice)
2022-08-05 09:56:48,945 INFO  [restartedMain] (SpringApplication.java:634)- No active profile set, falling back to 1 default profile: "default"
2022-08-05 09:56:48,986 INFO  [restartedMain] (DeferredLog.java:255)- Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-08-05 09:56:48,987 INFO  [restartedMain] (DeferredLog.java:255)- For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2022-08-05 09:56:49,749 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:262)- Multiple Spring Data modules found, entering strict repository configuration mode
2022-08-05 09:56:49,755 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:132)- Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-08-05 09:56:49,778 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:201)- Finished Spring Data repository scanning in 7 ms. Found 0 Redis repository interfaces.
2022-08-05 09:56:50,319 INFO  [restartedMain] (TomcatWebServer.java:108)- Tomcat initialized with port(s): 8081 (http)
2022-08-05 09:56:50,327 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing ProtocolHandler ["http-nio-8081"]
2022-08-05 09:56:50,327 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting service [Tomcat]
2022-08-05 09:56:50,327 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-08-05 09:56:50,398 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing Spring embedded WebApplicationContext
2022-08-05 09:56:50,399 INFO  [restartedMain] (ServletWebServerApplicationContext.java:292)- Root WebApplicationContext: initialization completed in 1412 ms
2022-08-05 09:56:50,663 INFO  [restartedMain] (SelectByMultiIdMethod.java:47)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-08-05 09:56:50,664 INFO  [restartedMain] (UpdateByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-08-05 09:56:50,664 INFO  [restartedMain] (DeleteByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-08-05 09:56:52,156 WARN  [restartedMain] (TableInfoHelper.java:342)- Can not find table primary key in Class: "com.swhy.swhypractice.pojo.RemoteServices".
2022-08-05 09:56:52,156 WARN  [restartedMain] (DefaultSqlInjector.java:56)- class com.swhy.swhypractice.pojo.RemoteServices ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2022-08-05 09:56:52,712 INFO  [restartedMain] (PropertySourcedRequestMappingHandlerMapping.java:69)- Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-08-05 09:56:52,726 ERROR  [restartedMain] (PlusConfig.java:62)- mpp.entityBasePath is null skip scan result map
2022-08-05 09:56:52,850 INFO  [restartedMain] (OptionalLiveReloadServer.java:58)- LiveReload server is running on port 35729
2022-08-05 09:56:52,869 INFO  [restartedMain] (WelcomePageHandlerMapping.java:53)- Adding welcome page: class path resource [static/index.html]
2022-08-05 09:56:53,049 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting ProtocolHandler ["http-nio-8081"]
2022-08-05 09:56:53,066 INFO  [restartedMain] (TomcatWebServer.java:220)- Tomcat started on port(s): 8081 (http) with context path ''
2022-08-05 09:56:53,067 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:160)- Context refreshed
2022-08-05 09:56:53,080 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:163)- Found 1 custom documentation plugin(s)
2022-08-05 09:56:53,101 INFO  [restartedMain] (ApiListingReferenceScanner.java:41)- Scanning for api listing references
2022-08-05 09:56:53,210 INFO  [http-nio-8081-exec-1] (DirectJDKLog.java:173)- Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-05 09:56:53,211 INFO  [http-nio-8081-exec-1] (FrameworkServlet.java:525)- Initializing Servlet 'dispatcherServlet'
2022-08-05 09:56:53,212 INFO  [http-nio-8081-exec-1] (FrameworkServlet.java:547)- Completed initialization in 1 ms
2022-08-05 09:56:53,253 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-08-05 09:56:53,255 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-08-05 09:56:53,258 INFO  [restartedMain] (StartupInfoLogger.java:61)- Started SwhyPracticeApplication in 4.747 seconds (JVM running for 8.361)
2022-08-05 09:56:53,848 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-08-05 09:56:53,877 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-08-05 09:56:54,036 INFO  [scheduling-1] (HikariDataSource.java:110)- HikariPool-1 - Starting...
2022-08-05 09:56:54,188 INFO  [scheduling-1] (HikariDataSource.java:123)- HikariPool-1 - Start completed.
2022-08-05 11:33:23,716 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketTimeoutException: Read timed out
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushProgressMessage(ScheduleConfig.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-08-05 11:41:30,689 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushHostMessage(ScheduleConfig.java:95)
	at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at com.jcraft.jsch.Util.createSocket(Util.java:343)
	... 16 common frames omitted
2022-08-05 11:41:51,716 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushProgressMessage(ScheduleConfig.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at com.jcraft.jsch.Util.createSocket(Util.java:343)
	... 16 common frames omitted
2022-08-05 11:46:32,423 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketTimeoutException: Read timed out
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushProgressMessage(ScheduleConfig.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-08-05 12:12:55,025 INFO  [SpringApplicationShutdownHook] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-08-05 12:12:55,026 INFO  [SpringApplicationShutdownHook] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-08-05 12:12:55,032 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
java.io.InterruptedIOException: null
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:328)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.exeCommand(SSHLinuxUtils.java:58)
	at com.swhy.swhypractice.service.ScheduleServices.pushProgressMessage(ScheduleConfig.java:56)
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-08-05 12:12:55,047 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:350)- HikariPool-1 - Shutdown initiated...
2022-08-05 12:12:55,051 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:352)- HikariPool-1 - Shutdown completed.
