2022-07-20 09:50:21,654 INFO  [main] (StartupInfoLogger.java:55)- Starting SwhyPracticeApplicationTests using Java 11.0.14 on SK-20211029DMIT with PID 9064 (started by Administrator in F:\swhyPractice)
2022-07-20 09:50:21,669 INFO  [main] (SpringApplication.java:634)- No active profile set, falling back to 1 default profile: "default"
2022-07-20 09:50:22,842 INFO  [main] (RepositoryConfigurationDelegate.java:262)- Multiple Spring Data modules found, entering strict repository configuration mode
2022-07-20 09:50:22,847 INFO  [main] (RepositoryConfigurationDelegate.java:132)- Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-07-20 09:50:22,874 INFO  [main] (RepositoryConfigurationDelegate.java:201)- Finished Spring Data repository scanning in 9 ms. Found 0 Redis repository interfaces.
2022-07-20 09:50:24,945 INFO  [main] (TomcatWebServer.java:108)- Tomcat initialized with port(s): 0 (http)
2022-07-20 09:50:24,959 INFO  [main] (DirectJDKLog.java:173)- Initializing ProtocolHandler ["http-nio-auto-1"]
2022-07-20 09:50:24,961 INFO  [main] (DirectJDKLog.java:173)- Starting service [Tomcat]
2022-07-20 09:50:24,961 INFO  [main] (DirectJDKLog.java:173)- Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-07-20 09:50:25,135 INFO  [main] (DirectJDKLog.java:173)- Initializing Spring embedded WebApplicationContext
2022-07-20 09:50:25,135 INFO  [main] (ServletWebServerApplicationContext.java:292)- Root WebApplicationContext: initialization completed in 3417 ms
2022-07-20 09:50:25,739 INFO  [main] (SelectByMultiIdMethod.java:47)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 09:50:25,740 INFO  [main] (UpdateByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 09:50:25,741 INFO  [main] (DeleteByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 09:50:27,701 WARN  [main] (TableInfoHelper.java:342)- Can not find table primary key in Class: "com.swhy.swhypractice.pojo.RemoteServices".
2022-07-20 09:50:27,702 WARN  [main] (DefaultSqlInjector.java:56)- class com.swhy.swhypractice.pojo.RemoteServices ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2022-07-20 09:50:28,704 INFO  [main] (PropertySourcedRequestMappingHandlerMapping.java:69)- Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-07-20 09:50:28,728 ERROR  [main] (PlusConfig.java:62)- mpp.entityBasePath is null skip scan result map
2022-07-20 09:50:28,955 INFO  [main] (WelcomePageHandlerMapping.java:53)- Adding welcome page: class path resource [static/index.html]
2022-07-20 09:50:29,375 INFO  [main] (DirectJDKLog.java:173)- Starting ProtocolHandler ["http-nio-auto-1"]
2022-07-20 09:50:29,396 INFO  [main] (TomcatWebServer.java:220)- Tomcat started on port(s): 51040 (http) with context path ''
2022-07-20 09:50:29,397 INFO  [main] (DocumentationPluginsBootstrapper.java:160)- Context refreshed
2022-07-20 09:50:29,441 INFO  [main] (DocumentationPluginsBootstrapper.java:163)- Found 1 custom documentation plugin(s)
2022-07-20 09:50:29,472 INFO  [main] (ApiListingReferenceScanner.java:41)- Scanning for api listing references
2022-07-20 09:50:29,678 INFO  [main] (StartupInfoLogger.java:61)- Started SwhyPracticeApplicationTests in 8.826 seconds (JVM running for 10.87)
2022-07-20 09:50:30,058 INFO  [scheduling-1] (HikariDataSource.java:110)- HikariPool-1 - Starting...
2022-07-20 09:50:30,338 INFO  [scheduling-1] (HikariDataSource.java:123)- HikariPool-1 - Start completed.
2022-07-20 09:50:32,247 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:350)- HikariPool-1 - Shutdown initiated...
2022-07-20 09:50:32,258 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:352)- HikariPool-1 - Shutdown completed.
2022-07-20 09:51:06,684 INFO  [restartedMain] (StartupInfoLogger.java:55)- Starting SwhyPracticeApplication using Java 11.0.14 on SK-20211029DMIT with PID 12448 (F:\swhyPractice\target\classes started by Administrator in F:\swhyPractice)
2022-07-20 09:51:06,685 INFO  [restartedMain] (SpringApplication.java:634)- No active profile set, falling back to 1 default profile: "default"
2022-07-20 09:51:06,721 INFO  [restartedMain] (DeferredLog.java:255)- Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-07-20 09:51:06,721 INFO  [restartedMain] (DeferredLog.java:255)- For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2022-07-20 09:51:07,405 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:262)- Multiple Spring Data modules found, entering strict repository configuration mode
2022-07-20 09:51:07,407 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:132)- Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-07-20 09:51:07,424 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:201)- Finished Spring Data repository scanning in 7 ms. Found 0 Redis repository interfaces.
2022-07-20 09:51:07,892 INFO  [restartedMain] (TomcatWebServer.java:108)- Tomcat initialized with port(s): 8081 (http)
2022-07-20 09:51:07,899 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing ProtocolHandler ["http-nio-8081"]
2022-07-20 09:51:07,900 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting service [Tomcat]
2022-07-20 09:51:07,900 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-07-20 09:51:07,968 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing Spring embedded WebApplicationContext
2022-07-20 09:51:07,968 INFO  [restartedMain] (ServletWebServerApplicationContext.java:292)- Root WebApplicationContext: initialization completed in 1246 ms
2022-07-20 09:51:08,187 INFO  [restartedMain] (SelectByMultiIdMethod.java:47)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 09:51:08,188 INFO  [restartedMain] (UpdateByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 09:51:08,189 INFO  [restartedMain] (DeleteByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 09:51:10,058 WARN  [restartedMain] (TableInfoHelper.java:342)- Can not find table primary key in Class: "com.swhy.swhypractice.pojo.RemoteServices".
2022-07-20 09:51:10,059 WARN  [restartedMain] (DefaultSqlInjector.java:56)- class com.swhy.swhypractice.pojo.RemoteServices ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2022-07-20 09:51:10,555 INFO  [restartedMain] (PropertySourcedRequestMappingHandlerMapping.java:69)- Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-07-20 09:51:10,570 ERROR  [restartedMain] (PlusConfig.java:62)- mpp.entityBasePath is null skip scan result map
2022-07-20 09:51:10,688 INFO  [restartedMain] (OptionalLiveReloadServer.java:58)- LiveReload server is running on port 35729
2022-07-20 09:51:10,708 INFO  [restartedMain] (WelcomePageHandlerMapping.java:53)- Adding welcome page: class path resource [static/index.html]
2022-07-20 09:51:10,894 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting ProtocolHandler ["http-nio-8081"]
2022-07-20 09:51:10,909 INFO  [restartedMain] (TomcatWebServer.java:220)- Tomcat started on port(s): 8081 (http) with context path ''
2022-07-20 09:51:10,910 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:160)- Context refreshed
2022-07-20 09:51:10,924 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:163)- Found 1 custom documentation plugin(s)
2022-07-20 09:51:10,943 INFO  [restartedMain] (ApiListingReferenceScanner.java:41)- Scanning for api listing references
2022-07-20 09:51:11,115 INFO  [restartedMain] (StartupInfoLogger.java:61)- Started SwhyPracticeApplication in 4.771 seconds (JVM running for 7.165)
2022-07-20 09:51:12,038 INFO  [scheduling-1] (HikariDataSource.java:110)- HikariPool-1 - Starting...
2022-07-20 09:51:12,147 INFO  [scheduling-1] (HikariDataSource.java:123)- HikariPool-1 - Start completed.
2022-07-20 09:55:12,081 INFO  [http-nio-8081-exec-2] (DirectJDKLog.java:173)- Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-07-20 09:55:12,081 INFO  [http-nio-8081-exec-2] (FrameworkServlet.java:525)- Initializing Servlet 'dispatcherServlet'
2022-07-20 09:55:12,083 INFO  [http-nio-8081-exec-2] (FrameworkServlet.java:547)- Completed initialization in 2 ms
2022-07-20 09:55:12,132 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 09:55:12,135 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 09:55:12,135 INFO  [http-nio-8081-exec-2] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 09:55:20,738 ERROR  [http-nio-8081-exec-7] (DirectJDKLog.java:175)- Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NumberFormatException: null] with root cause
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.swhy.swhypractice.controller.PropController.deleteProp(MyController.java:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 09:56:39,436 INFO  [http-nio-8081-exec-4] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 09:56:40,426 INFO  [http-nio-8081-exec-5] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 09:56:40,547 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 09:56:40,548 INFO  [http-nio-8081-exec-6] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:01:05,275 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 10:01:05,277 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:01:05,277 INFO  [http-nio-8081-exec-5] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:01:53,143 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 10:02:01,966 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 10:02:01,967 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:02:01,967 INFO  [http-nio-8081-exec-4] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:02:02,782 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 10:02:02,782 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:02:07,744 INFO  [http-nio-8081-exec-10] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:02:07,745 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:02:07,745 INFO  [http-nio-8081-exec-1] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:03:26,572 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:03:28,675 INFO  [http-nio-8081-exec-10] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:03:28,677 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:03:28,677 INFO  [http-nio-8081-exec-2] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:04:02,537 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:04:06,328 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:04:06,329 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:04:06,329 INFO  [http-nio-8081-exec-7] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:04:33,308 INFO  [http-nio-8081-exec-7] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:04:33,842 INFO  [http-nio-8081-exec-8] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:04:33,857 INFO  [http-nio-8081-exec-9] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:04:33,857 INFO  [http-nio-8081-exec-9] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:09:19,029 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:09:20,015 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:09:20,068 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:09:20,068 INFO  [http-nio-8081-exec-8] (WebSocket.java:80)- 【websocket消息】广播消息:hello
2022-07-20 10:10:09,360 INFO  [SpringApplicationShutdownHook] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:10:09,379 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:350)- HikariPool-1 - Shutdown initiated...
2022-07-20 10:10:09,386 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:352)- HikariPool-1 - Shutdown completed.
2022-07-20 10:10:16,422 INFO  [restartedMain] (StartupInfoLogger.java:55)- Starting SwhyPracticeApplication using Java 11.0.14 on SK-20211029DMIT with PID 13900 (F:\swhyPractice\target\classes started by Administrator in F:\swhyPractice)
2022-07-20 10:10:16,423 INFO  [restartedMain] (SpringApplication.java:634)- No active profile set, falling back to 1 default profile: "default"
2022-07-20 10:10:16,459 INFO  [restartedMain] (DeferredLog.java:255)- Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-07-20 10:10:16,459 INFO  [restartedMain] (DeferredLog.java:255)- For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2022-07-20 10:10:17,135 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:262)- Multiple Spring Data modules found, entering strict repository configuration mode
2022-07-20 10:10:17,136 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:132)- Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-07-20 10:10:17,153 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:201)- Finished Spring Data repository scanning in 6 ms. Found 0 Redis repository interfaces.
2022-07-20 10:10:17,623 INFO  [restartedMain] (TomcatWebServer.java:108)- Tomcat initialized with port(s): 8081 (http)
2022-07-20 10:10:17,629 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing ProtocolHandler ["http-nio-8081"]
2022-07-20 10:10:17,630 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting service [Tomcat]
2022-07-20 10:10:17,630 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-07-20 10:10:17,692 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing Spring embedded WebApplicationContext
2022-07-20 10:10:17,692 INFO  [restartedMain] (ServletWebServerApplicationContext.java:292)- Root WebApplicationContext: initialization completed in 1232 ms
2022-07-20 10:10:17,906 INFO  [restartedMain] (SelectByMultiIdMethod.java:47)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 10:10:17,907 INFO  [restartedMain] (UpdateByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 10:10:17,907 INFO  [restartedMain] (DeleteByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 10:10:19,785 WARN  [restartedMain] (TableInfoHelper.java:342)- Can not find table primary key in Class: "com.swhy.swhypractice.pojo.RemoteServices".
2022-07-20 10:10:19,786 WARN  [restartedMain] (DefaultSqlInjector.java:56)- class com.swhy.swhypractice.pojo.RemoteServices ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2022-07-20 10:10:20,244 INFO  [restartedMain] (PropertySourcedRequestMappingHandlerMapping.java:69)- Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-07-20 10:10:20,258 ERROR  [restartedMain] (PlusConfig.java:62)- mpp.entityBasePath is null skip scan result map
2022-07-20 10:10:20,367 INFO  [restartedMain] (OptionalLiveReloadServer.java:58)- LiveReload server is running on port 35729
2022-07-20 10:10:20,384 INFO  [restartedMain] (WelcomePageHandlerMapping.java:53)- Adding welcome page: class path resource [static/index.html]
2022-07-20 10:10:20,550 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting ProtocolHandler ["http-nio-8081"]
2022-07-20 10:10:20,568 INFO  [restartedMain] (TomcatWebServer.java:220)- Tomcat started on port(s): 8081 (http) with context path ''
2022-07-20 10:10:20,570 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:160)- Context refreshed
2022-07-20 10:10:20,587 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:163)- Found 1 custom documentation plugin(s)
2022-07-20 10:10:20,610 INFO  [restartedMain] (ApiListingReferenceScanner.java:41)- Scanning for api listing references
2022-07-20 10:10:20,872 INFO  [restartedMain] (StartupInfoLogger.java:61)- Started SwhyPracticeApplication in 4.79 seconds (JVM running for 6.675)
2022-07-20 10:10:21,027 INFO  [scheduling-1] (HikariDataSource.java:110)- HikariPool-1 - Starting...
2022-07-20 10:10:21,128 INFO  [scheduling-1] (HikariDataSource.java:123)- HikariPool-1 - Start completed.
2022-07-20 10:10:29,091 INFO  [http-nio-8081-exec-2] (DirectJDKLog.java:173)- Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-07-20 10:10:29,092 INFO  [http-nio-8081-exec-2] (FrameworkServlet.java:525)- Initializing Servlet 'dispatcherServlet'
2022-07-20 10:10:29,095 INFO  [http-nio-8081-exec-2] (FrameworkServlet.java:547)- Completed initialization in 3 ms
2022-07-20 10:10:29,194 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:10:29,197 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:12:01,145 INFO  [http-nio-8081-exec-1] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:32:25,072 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:32:25,103 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:35:22,969 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:35:23,904 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:35:23,999 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:35:50,899 INFO  [http-nio-8081-exec-7] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:38:39,769 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:38:39,787 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:40:14,344 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:40:15,461 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:40:15,556 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:40:46,597 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:40:47,588 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:40:47,606 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:42:41,250 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:43:27,757 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:43:27,799 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:44:08,638 INFO  [http-nio-8081-exec-7] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:44:09,640 INFO  [http-nio-8081-exec-8] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:44:09,700 INFO  [http-nio-8081-exec-10] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:44:41,047 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:44:41,583 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:44:41,619 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:49:48,373 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:49:49,171 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:49:49,229 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:50:31,433 INFO  [http-nio-8081-exec-4] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:50:33,637 INFO  [http-nio-8081-exec-5] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:50:33,674 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:50:45,684 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:50:46,216 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:50:46,253 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:52:41,275 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:53:24,217 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:53:24,266 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:53:38,252 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:53:39,323 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:53:39,416 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:53:59,013 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 10:53:59,557 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 10:53:59,593 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 10:59:57,552 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:00:04,589 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:00:04,672 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:01:04,943 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:01:18,901 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:01:18,944 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:05:08,909 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:05:09,872 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:05:09,933 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:06:43,374 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:06:43,899 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:06:43,935 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:07:20,313 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:07:20,839 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:07:20,871 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:07:49,371 INFO  [http-nio-8081-exec-7] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:07:49,891 INFO  [http-nio-8081-exec-8] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:07:49,925 INFO  [http-nio-8081-exec-10] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:08:00,457 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:08:02,087 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:08:02,128 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:11:59,802 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:12:01,801 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:12:01,855 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:18:07,268 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 11:18:07,798 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 11:18:07,932 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 11:19:58,999 INFO  [http-nio-8081-exec-10] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 11:19:59,131 INFO  [http-nio-8081-exec-9] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 12:06:29,091 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 12:06:29,091 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 12:06:30,112 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 12:06:30,235 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 12:09:07,085 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 12:09:07,202 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 12:09:26,528 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 12:09:26,528 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 12:09:27,489 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 12:09:27,572 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 12:11:10,785 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 12:11:10,936 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 13:22:45,055 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at com.jcraft.jsch.Util.createSocket(Util.java:343)
	... 16 common frames omitted
2022-07-20 13:23:09,077 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at com.jcraft.jsch.Util.createSocket(Util.java:343)
	... 16 common frames omitted
2022-07-20 13:34:59,287 INFO  [SpringApplicationShutdownHook] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 13:34:59,288 INFO  [SpringApplicationShutdownHook] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 13:34:59,324 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:350)- HikariPool-1 - Shutdown initiated...
2022-07-20 13:34:59,331 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:352)- HikariPool-1 - Shutdown completed.
2022-07-20 16:19:51,328 INFO  [restartedMain] (StartupInfoLogger.java:55)- Starting SwhyPracticeApplication using Java 11.0.14 on SK-20211029DMIT with PID 16796 (F:\swhyPractice\target\classes started by Administrator in F:\swhyPractice)
2022-07-20 16:19:51,334 INFO  [restartedMain] (SpringApplication.java:634)- No active profile set, falling back to 1 default profile: "default"
2022-07-20 16:19:51,444 INFO  [restartedMain] (DeferredLog.java:255)- Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-07-20 16:19:51,444 INFO  [restartedMain] (DeferredLog.java:255)- For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2022-07-20 16:19:52,690 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:262)- Multiple Spring Data modules found, entering strict repository configuration mode
2022-07-20 16:19:52,697 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:132)- Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-07-20 16:19:52,741 INFO  [restartedMain] (RepositoryConfigurationDelegate.java:201)- Finished Spring Data repository scanning in 17 ms. Found 0 Redis repository interfaces.
2022-07-20 16:19:53,825 INFO  [restartedMain] (TomcatWebServer.java:108)- Tomcat initialized with port(s): 8081 (http)
2022-07-20 16:19:53,844 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing ProtocolHandler ["http-nio-8081"]
2022-07-20 16:19:53,845 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting service [Tomcat]
2022-07-20 16:19:53,845 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-07-20 16:19:53,974 INFO  [restartedMain] (DirectJDKLog.java:173)- Initializing Spring embedded WebApplicationContext
2022-07-20 16:19:53,975 INFO  [restartedMain] (ServletWebServerApplicationContext.java:292)- Root WebApplicationContext: initialization completed in 2530 ms
2022-07-20 16:19:54,488 INFO  [restartedMain] (SelectByMultiIdMethod.java:47)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 16:19:54,490 INFO  [restartedMain] (UpdateByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 16:19:54,490 INFO  [restartedMain] (DeleteByMultiIdMethod.java:45)- entity com.swhy.swhypractice.pojo.RemoteProp not contain MppMultiId anno
2022-07-20 16:19:56,848 WARN  [restartedMain] (TableInfoHelper.java:342)- Can not find table primary key in Class: "com.swhy.swhypractice.pojo.RemoteServices".
2022-07-20 16:19:56,848 WARN  [restartedMain] (DefaultSqlInjector.java:56)- class com.swhy.swhypractice.pojo.RemoteServices ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2022-07-20 16:19:57,546 INFO  [restartedMain] (PropertySourcedRequestMappingHandlerMapping.java:69)- Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-07-20 16:19:57,569 ERROR  [restartedMain] (PlusConfig.java:62)- mpp.entityBasePath is null skip scan result map
2022-07-20 16:19:57,706 INFO  [restartedMain] (OptionalLiveReloadServer.java:58)- LiveReload server is running on port 35729
2022-07-20 16:19:57,746 INFO  [restartedMain] (WelcomePageHandlerMapping.java:53)- Adding welcome page: class path resource [static/index.html]
2022-07-20 16:19:58,044 INFO  [restartedMain] (DirectJDKLog.java:173)- Starting ProtocolHandler ["http-nio-8081"]
2022-07-20 16:19:58,070 INFO  [restartedMain] (TomcatWebServer.java:220)- Tomcat started on port(s): 8081 (http) with context path ''
2022-07-20 16:19:58,072 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:160)- Context refreshed
2022-07-20 16:19:58,095 INFO  [restartedMain] (DocumentationPluginsBootstrapper.java:163)- Found 1 custom documentation plugin(s)
2022-07-20 16:19:58,127 INFO  [restartedMain] (ApiListingReferenceScanner.java:41)- Scanning for api listing references
2022-07-20 16:19:58,299 INFO  [restartedMain] (StartupInfoLogger.java:61)- Started SwhyPracticeApplication in 7.824 seconds (JVM running for 11.435)
2022-07-20 16:19:58,466 INFO  [http-nio-8081-exec-1] (DirectJDKLog.java:173)- Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-07-20 16:19:58,466 INFO  [http-nio-8081-exec-1] (FrameworkServlet.java:525)- Initializing Servlet 'dispatcherServlet'
2022-07-20 16:19:58,467 INFO  [http-nio-8081-exec-1] (FrameworkServlet.java:547)- Completed initialization in 1 ms
2022-07-20 16:19:58,503 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 16:19:58,503 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 16:19:58,505 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:19:58,505 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:20:00,059 INFO  [scheduling-1] (HikariDataSource.java:110)- HikariPool-1 - Starting...
2022-07-20 16:20:00,221 INFO  [scheduling-1] (HikariDataSource.java:123)- HikariPool-1 - Start completed.
2022-07-20 16:20:00,427 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:3
2022-07-20 16:20:00,428 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:20:10,150 INFO  [http-nio-8081-exec-8] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:4
2022-07-20 16:20:10,151 INFO  [http-nio-8081-exec-9] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:20:10,716 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:3
2022-07-20 16:20:10,716 INFO  [http-nio-8081-exec-4] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:2
2022-07-20 16:20:10,716 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:20:10,716 INFO  [http-nio-8081-exec-1] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 16:20:11,510 INFO  [http-nio-8081-exec-5] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:20:11,526 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:21:19,270 INFO  [http-nio-8081-exec-10] (MyController.java:106)- 查询进程返回结果：root       965     1  0 Jul12 ?        00:00:39 /usr/sbin/sshd -D
2022-07-20 16:21:19,431 INFO  [http-nio-8081-exec-10] (MyController.java:112)- remote_service保存结果:true
2022-07-20 16:21:19,449 INFO  [http-nio-8081-exec-10] (MyController.java:114)- remote_prop保存结果:true
2022-07-20 16:21:28,428 INFO  [http-nio-8081-exec-4] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:21:29,037 INFO  [http-nio-8081-exec-5] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:21:29,101 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:21:57,512 INFO  [http-nio-8081-exec-7] (MyController.java:106)- 查询进程返回结果：root         1     0  0 Jul12 ?        00:02:19 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
2022-07-20 16:21:57,520 INFO  [http-nio-8081-exec-7] (MyController.java:112)- remote_service保存结果:true
2022-07-20 16:21:57,523 INFO  [http-nio-8081-exec-7] (MyController.java:114)- remote_prop保存结果:true
2022-07-20 16:22:31,142 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:22:31,632 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:22:31,706 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:24:10,850 INFO  [http-nio-8081-exec-6] (MyController.java:106)- 查询进程返回结果：root         2     0  0 Jul12 ?        00:00:00 [kthreadd]
2022-07-20 16:24:10,858 INFO  [http-nio-8081-exec-6] (MyController.java:112)- remote_service保存结果:true
2022-07-20 16:24:10,861 INFO  [http-nio-8081-exec-6] (MyController.java:114)- remote_prop保存结果:true
2022-07-20 16:24:14,145 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:24:14,578 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:24:14,677 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:24:37,568 INFO  [http-nio-8081-exec-5] (MyController.java:106)- 查询进程返回结果：root         9     2  0 Jul12 ?        00:03:56 [rcu_sched]
2022-07-20 16:24:37,575 INFO  [http-nio-8081-exec-5] (MyController.java:112)- remote_service保存结果:true
2022-07-20 16:24:37,579 INFO  [http-nio-8081-exec-5] (MyController.java:114)- remote_prop保存结果:true
2022-07-20 16:24:42,528 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:24:42,965 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:24:43,061 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:27:32,523 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 16:27:32,564 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:27:59,358 INFO  [http-nio-8081-exec-6] (MyController.java:158)- 被删除的配置：RemoteServices(address=121.89.201.223, pid=1)
2022-07-20 16:28:28,102 INFO  [http-nio-8081-exec-2] (MyController.java:106)- 查询进程返回结果：root         1     0  0 Jul12 ?        00:02:20 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
2022-07-20 16:28:28,109 INFO  [http-nio-8081-exec-2] (MyController.java:112)- remote_service保存结果:true
2022-07-20 16:28:28,113 INFO  [http-nio-8081-exec-2] (MyController.java:114)- remote_prop保存结果:true
2022-07-20 16:28:28,185 INFO  [http-nio-8081-exec-3] (MyController.java:106)- 查询进程返回结果：root         1     0  0 Jul12 ?        00:02:20 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
2022-07-20 16:28:28,191 INFO  [http-nio-8081-exec-3] (MyController.java:112)- remote_service保存结果:true
2022-07-20 16:28:28,194 INFO  [http-nio-8081-exec-3] (MyController.java:114)- remote_prop保存结果:true
2022-07-20 16:30:49,335 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:3
2022-07-20 16:30:49,396 INFO  [http-nio-8081-exec-10] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:40:53,384 INFO  [http-nio-8081-exec-1] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:2
2022-07-20 16:40:53,384 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 16:40:53,384 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:40:54,296 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:40:54,398 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:42:01,694 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 16:42:01,734 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:45:08,874 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:3
2022-07-20 16:45:08,906 INFO  [http-nio-8081-exec-1] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:46:08,228 INFO  [http-nio-8081-exec-10] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:4
2022-07-20 16:46:08,230 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:47:06,879 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:5
2022-07-20 16:47:06,929 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:47:26,281 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:4
2022-07-20 16:47:26,281 INFO  [http-nio-8081-exec-1] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:3
2022-07-20 16:47:26,282 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:2
2022-07-20 16:47:26,282 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 16:47:26,283 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:47:27,185 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:47:27,293 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:49:34,243 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:49:35,187 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:49:35,276 INFO  [http-nio-8081-exec-8] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:50:42,751 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 16:50:42,790 INFO  [http-nio-8081-exec-10] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:50:57,597 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:3
2022-07-20 16:50:57,654 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:52:50,155 INFO  [http-nio-8081-exec-3] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:4
2022-07-20 16:52:50,160 INFO  [http-nio-8081-exec-4] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:55:01,111 INFO  [http-nio-8081-exec-6] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:5
2022-07-20 16:55:01,224 INFO  [http-nio-8081-exec-7] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:55:33,540 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:3
2022-07-20 16:55:33,540 INFO  [http-nio-8081-exec-7] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:2
2022-07-20 16:55:33,541 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 16:55:33,540 INFO  [http-nio-8081-exec-4] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:4
2022-07-20 16:55:33,542 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:55:34,459 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:55:34,555 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:56:36,264 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:56:37,254 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:56:37,420 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 16:58:02,111 INFO  [http-nio-8081-exec-5] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 16:58:02,876 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 16:58:02,982 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:00:15,799 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:00:16,728 INFO  [http-nio-8081-exec-1] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 17:00:16,811 INFO  [http-nio-8081-exec-2] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:01:25,922 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:01:26,871 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 17:01:26,973 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:04:54,274 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:04:55,251 INFO  [http-nio-8081-exec-10] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 17:04:55,347 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:05:39,551 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:05:40,512 INFO  [http-nio-8081-exec-9] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 17:05:40,612 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:10:50,093 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 17:10:50,095 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:11:03,218 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:3
2022-07-20 17:11:03,220 INFO  [http-nio-8081-exec-10] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:11:30,136 INFO  [http-nio-8081-exec-4] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:4
2022-07-20 17:11:30,188 INFO  [http-nio-8081-exec-6] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:11:43,005 INFO  [http-nio-8081-exec-2] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:3
2022-07-20 17:11:43,005 INFO  [http-nio-8081-exec-10] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:2
2022-07-20 17:11:43,005 INFO  [http-nio-8081-exec-9] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 17:11:43,006 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:11:43,944 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 17:11:44,049 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:12:25,770 INFO  [http-nio-8081-exec-3] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:12:26,716 INFO  [http-nio-8081-exec-7] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:1
2022-07-20 17:12:26,836 INFO  [http-nio-8081-exec-5] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:15:03,045 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:06,049 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:09,042 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:12,048 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:15,056 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:18,048 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:21,043 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:22,910 ERROR  [http-nio-8081-exec-3] (DirectJDKLog.java:175)- Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset] with root cause
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.controller.PropController.showProp(MyController.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:24,052 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:27,058 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:30,093 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:33,044 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:36,056 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:39,048 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:42,048 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:45,051 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:48,056 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:51,049 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:54,050 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:15:57,048 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:00,044 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:03,049 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:06,042 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:09,044 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:12,051 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:15,044 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:18,051 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:21,055 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:24,054 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:27,048 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:16:30,041 ERROR  [scheduling-1] (TaskUtils.java:95)- Unexpected error occurred in scheduled task
com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.swhy.swhypractice.utils.SSHLinuxUtils.createSession(SSHLinuxUtils.java:35)
	at com.swhy.swhypractice.service.ScheduleServices.pushMessage(ScheduleConfig.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-07-20 17:31:24,898 INFO  [http-nio-8081-exec-2] (WebSocket.java:39)- 【websocket消息】有新的连接，总数为:2
2022-07-20 17:31:24,946 INFO  [http-nio-8081-exec-3] (WebSocket.java:61)- 【websocket消息】收到客户端消息:{"连接":"成功"}
2022-07-20 17:40:44,617 INFO  [http-nio-8081-exec-6] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:1
2022-07-20 17:40:44,619 INFO  [http-nio-8081-exec-8] (WebSocket.java:51)- 【websocket消息】连接断开，总数为:0
2022-07-20 17:40:51,054 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:350)- HikariPool-1 - Shutdown initiated...
2022-07-20 17:40:51,057 INFO  [SpringApplicationShutdownHook] (HikariDataSource.java:352)- HikariPool-1 - Shutdown completed.
